export const CREATE_BOOK_REQUEST = 'CREATE_BOOK_REQUEST'

export const GET_BOOK_LIST_REQUEST = 'GET_BOOK_LIST_REQUEST'
export const GET_BOOK_LIST_SUCCESS = 'GET_BOOK_LIST_SUCCESS'

export const GET_BOOK_REQUEST = 'GET_BOOK_REQUEST'
export const GET_BOOK_SUCCESS = 'GET_BOOK_SUCCESS'

export const UPDATE_BOOK_REQUEST = 'UPDATE_BOOK_REQUEST'

export const DELETE_BOOK_REQUEST = 'DELETE_BOOK_REQUEST'

export const CRAWL_BOOK_REQUEST = 'CRAWL_BOOK_REQUEST'
export const CRAWL_BOOK_SUCCESS = 'CRAWL_BOOK_SUCCESS'

export const CHANGE_BOOK_DATA = 'CHANGE_BOOK_DATA'
