export const LOAD_NEW_BOOK = 'LOAD_NEW_BOOK'

export const CHANGE_NEW_BOOK_DATA = 'CHANGE_NEW_BOOK_DATA'

export const CREATE_NEW_BOOK_REQUEST = 'CREATE_NEW_BOOK_REQUEST'
export const CREATE_NEW_BOOK_SUCCESS = 'CREATE_NEW_BOOK_SUCCESS'
